### ISSUE TITLE
Add robot meta tag to source

### ISSUE THREAD

**Issue by wbentley15** [ansible-community/community-website#322] opened 2023-11-30 21:47 UTC
Please add the following HTML tag to all website pages:
<meta name="robots" content="none">

**Comment by oraNod** [comment] 2023-12-01 10:09
@wbentley15 hi. it looks like the tag wasn't included in your comment. could you please update that?

**Comment by wbentley15** [comment] 2024-01-04 16:31
My bad...here it is: 
<meta name="robots" content="none">

**Comment by oraNod** [comment] 2024-01-05 09:26
@wbentley15 I'd just like to double check and maybe get the reasoning here. The `content="none"` directive would prevent the site from being returned in search results. Is this really what we want to do?

https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#directives

I'm speculating but is the motivation so that searches for "Ansible" would point to the Red Hat site rather than the community site?

**Comment by oraNod** [comment] 2024-01-05 12:51
This also relates to #355

**Comment by wbentley15** [comment] 2024-01-16 20:54
@oraNod I was asked to include these tags and I am sure they did not want to have the effects your described.  The intended point was to keep bots off the site.  As long as we have that covered, this issue can be marked as closed/ignored.

**Comment by oraNod** [comment] 2024-01-17 09:33
Thanks for the explanation @wbentley15 My understanding of the robots metadata is limited so my speculation in the previous comment might not have even made sense. I'll ask some colleagues who are a lot more versed in this area and get back to you soon.

**Comment by oraNod** [comment] 2024-01-19 11:18
I've reached out to the very helpful JP Sherman within Red Hat for advice on that meta and copied you on the thread @wbentley15 - JP confirmed my thoughts that `meta name="robots" content="none"` would have the effect of keeping *all* bots off the site, which would have negative impact on search results for the `ansible.com` domain. JP also gave some guidance on how we can filter bots via `robots.txt` and keep malicious and unwanted bots off the site, which should be in keeping with the intent of the request.

I've opened #385 to combine this issue with another and come up with a plan for `robots.txt` before launch. I'll go ahead and close this issue but please feel free to reopen or let me know if I've got anything wrong here. Thanks.

**Closed by oraNod** 2024-01-19 11:18 UTC
Labels: blocker
